### PR TITLE
Add: a index.html page and an image

### PR DESCRIPTION
**Pull request by ZhangZiboMono**
please pull my branch

### CODE REVIEW

**Review by linrongling48 — COMMENTED** [review]
Good

**Review by linrongling48 — APPROVED** [review]

**Review by linrongling48 — APPROVED** [review]

**Review by ZhangZiboMono — COMMENTED** [review]
good

**Review by linrongling48 — DISMISSED** [review]
哈哈哈哈

**Review by linrongling48 — APPROVED** [review]
Good

**Pull request merged**
